// Employee data and type for use in EmployeeManagement and other screens
export type Employee = {
  name: string;
  id: string;
  role: string;
  shift: string;
  clockIn: string;
  status: string;
  department: string;
  joined: string;
  phone: string;
  email: string;
  emergency: string;
  defaultShift: string;
  avgClockIn: string;
  preferredDayOff: string;
  totalHours: number;
  overtime: number;
  tasks: number;
  rating: number;
  productSales: number[];
  productSalesLabels: string[];
  salary: number; // annual salary in USD
  hourlyRate: number; // hourly rate in USD
  payType: 'salary' | 'hourly';
};

export const employees: Employee[] = [
  {
    name: "Ayesha Rahman",
    id: "EMP-1023",
    role: "Store Supervisor",
    shift: "09:00 AM - 05:00 PM",
    clockIn: "8:57 AM",
    status: "Active",
    department: "Sales",
    joined: "March 2023",
    phone: "+880 17XXXXXXXX",
    email: "ayesha@company.com",
    emergency: "017XXXXXXXX",
    defaultShift: "09:00 AM - 05:00 PM",
    avgClockIn: "9:05 AM",
    preferredDayOff: "Friday",
    totalHours: 439,
    overtime: 3,
    tasks: 17,
    rating: 4.3,
    productSales: [4, 9, 6, 8, 8, 7],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel", "Apparel"],
    salary: 62400, // $1200/week * 52
    hourlyRate: 30,
    payType: 'salary',
  },
  {
    name: "Sohel Mia",
    id: "EMP-1024",
    role: "Cashier",
    shift: "10:00 AM - 06:00 PM",
    clockIn: "9:59 AM",
    status: "Active",
    department: "Sales",
    joined: "April 2022",
    phone: "+880 18XXXXXXXX",
    email: "sohel@company.com",
    emergency: "018XXXXXXXX",
    defaultShift: "10:00 AM - 06:00 PM",
    avgClockIn: "10:10 AM",
    preferredDayOff: "Saturday",
    totalHours: 410,
    overtime: 2,
    tasks: 15,
    rating: 4.1,
    productSales: [5, 8, 7, 6, 7, 8],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 48000, // $900/week * 52
    hourlyRate: 25,
    payType: 'salary',
  },
  {
    name: "Jannatul Ferdous",
    id: "EMP-1025",
    role: "Sales Associate",
    shift: "11:00 AM - 07:00 PM",
    clockIn: "10:55 AM",
    status: "On Leave",
    department: "Sales",
    joined: "May 2021",
    phone: "+880 19XXXXXXXX",
    email: "jannatul@company.com",
    emergency: "019XXXXXXXX",
    defaultShift: "11:00 AM - 07:00 PM",
    avgClockIn: "11:15 AM",
    preferredDayOff: "Sunday",
    totalHours: 390,
    overtime: 1,
    tasks: 13,
    rating: 4.0,
    productSales: [6, 7, 8, 5, 6, 7],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 45000, // $850/week * 52
    hourlyRate: 23,
    payType: 'salary',
  },
  {
    name: "Rahim Uddin",
    id: "EMP-1026",
    role: "Inventory Manager",
    shift: "08:00 AM - 04:00 PM",
    clockIn: "7:58 AM",
    status: "Active",
    department: "Inventory",
    joined: "June 2020",
    phone: "+880 16XXXXXXXX",
    email: "rahim@company.com",
    emergency: "016XXXXXXXX",
    defaultShift: "08:00 AM - 04:00 PM",
    avgClockIn: "8:10 AM",
    preferredDayOff: "Monday",
    totalHours: 420,
    overtime: 4,
    tasks: 18,
    rating: 4.5,
    productSales: [7, 6, 7, 8, 7, 6],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 50000, // $950/week * 52
    hourlyRate: 24,
    payType: 'salary',
  },
  {
    name: "Fatema Begum",
    id: "EMP-1027",
    role: "Store Supervisor",
    shift: "09:00 AM - 05:00 PM",
    clockIn: "8:59 AM",
    status: "Active",
    department: "Sales",
    joined: "July 2021",
    phone: "+880 15XXXXXXXX",
    email: "fatema@company.com",
    emergency: "015XXXXXXXX",
    defaultShift: "09:00 AM - 05:00 PM",
    avgClockIn: "9:00 AM",
    preferredDayOff: "Wednesday",
    totalHours: 400,
    overtime: 2,
    tasks: 14,
    rating: 4.2,
    productSales: [8, 7, 6, 7, 8, 7],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 55000, // $1050/week * 52
    hourlyRate: 26,
    payType: 'salary',
  },
  {
    name: "Imran Hossain",
    id: "EMP-1028",
    role: "Cashier",
    shift: "10:00 AM - 06:00 PM",
    clockIn: "10:01 AM",
    status: "Absent",
    department: "Sales",
    joined: "August 2021",
    phone: "+880 14XXXXXXXX",
    email: "imran@company.com",
    emergency: "014XXXXXXXX",
    defaultShift: "10:00 AM - 06:00 PM",
    avgClockIn: "10:20 AM",
    preferredDayOff: "Thursday",
    totalHours: 380,
    overtime: 1,
    tasks: 12,
    rating: 3.9,
    productSales: [5, 6, 7, 5, 6, 5],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 42000, // $800/week * 52
    hourlyRate: 22,
    payType: 'salary',
  },
  {
    name: "Nusrat Jahan",
    id: "EMP-1029",
    role: "Sales Associate",
    shift: "11:00 AM - 07:00 PM",
    clockIn: "11:05 AM",
    status: "Active",
    department: "Sales",
    joined: "September 2020",
    phone: "+880 13XXXXXXXX",
    email: "nusrat@company.com",
    emergency: "013XXXXXXXX",
    defaultShift: "11:00 AM - 07:00 PM",
    avgClockIn: "11:10 AM",
    preferredDayOff: "Friday",
    totalHours: 395,
    overtime: 2,
    tasks: 14,
    rating: 4.0,
    productSales: [6, 7, 6, 7, 6, 7],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 45000, // $850/week * 52
    hourlyRate: 23,
    payType: 'salary',
  },
  {
    name: "Sabbir Ahmed",
    id: "EMP-1030",
    role: "Inventory Manager",
    shift: "08:00 AM - 04:00 PM",
    clockIn: "8:00 AM",
    status: "Active",
    department: "Inventory",
    joined: "October 2019",
    phone: "+880 12XXXXXXXX",
    email: "sabbir@company.com",
    emergency: "012XXXXXXXX",
    defaultShift: "08:00 AM - 04:00 PM",
    avgClockIn: "8:05 AM",
    preferredDayOff: "Saturday",
    totalHours: 430,
    overtime: 3,
    tasks: 16,
    rating: 4.4,
    productSales: [7, 8, 7, 8, 7, 8],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 50000, // $950/week * 52
    hourlyRate: 24,
    payType: 'salary',
  },
  {
    name: "Mitu Akter",
    id: "EMP-1031",
    role: "Store Supervisor",
    shift: "09:00 AM - 05:00 PM",
    clockIn: "9:10 AM",
    status: "On Leave",
    department: "Sales",
    joined: "November 2022",
    phone: "+880 11XXXXXXXX",
    email: "mitu@company.com",
    emergency: "011XXXXXXXX",
    defaultShift: "09:00 AM - 05:00 PM",
    avgClockIn: "9:15 AM",
    preferredDayOff: "Sunday",
    totalHours: 370,
    overtime: 1,
    tasks: 11,
    rating: 3.8,
    productSales: [5, 6, 5, 6, 5, 6],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 55000, // $1050/week * 52
    hourlyRate: 26,
    payType: 'salary',
  },
  {
    name: "Rashed Khan",
    id: "EMP-1032",
    role: "Cashier",
    shift: "10:00 AM - 06:00 PM",
    clockIn: "10:00 AM",
    status: "Active",
    department: "Sales",
    joined: "December 2021",
    phone: "+880 10XXXXXXXX",
    email: "rashed@company.com",
    emergency: "010XXXXXXXX",
    defaultShift: "10:00 AM - 06:00 PM",
    avgClockIn: "10:05 AM",
    preferredDayOff: "Monday",
    totalHours: 385,
    overtime: 2,
    tasks: 13,
    rating: 4.0,
    productSales: [6, 7, 6, 7, 6, 7],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 42000, // $800/week * 52
    hourlyRate: 22,
    payType: 'salary',
  },
  {
    name: "Shamim Reza",
    id: "EMP-1033",
    role: "Sales Associate",
    shift: "11:00 AM - 07:00 PM",
    clockIn: "11:10 AM",
    status: "Active",
    department: "Sales",
    joined: "January 2020",
    phone: "+880 19YYYYYYYY",
    email: "shamim@company.com",
    emergency: "019YYYYYYYY",
    defaultShift: "11:00 AM - 07:00 PM",
    avgClockIn: "11:20 AM",
    preferredDayOff: "Thursday",
    totalHours: 390,
    overtime: 1,
    tasks: 12,
    rating: 3.9,
    productSales: [5, 6, 7, 5, 6, 5],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 45000, // $850/week * 52
    hourlyRate: 23,
    payType: 'salary',
  },
  {
    name: "Tania Sultana",
    id: "EMP-1034",
    role: "Inventory Manager",
    shift: "08:00 AM - 04:00 PM",
    clockIn: "8:05 AM",
    status: "Active",
    department: "Inventory",
    joined: "February 2021",
    phone: "+880 18YYYYYYYY",
    email: "tania@company.com",
    emergency: "018YYYYYYYY",
    defaultShift: "08:00 AM - 04:00 PM",
    avgClockIn: "8:15 AM",
    preferredDayOff: "Friday",
    totalHours: 420,
    overtime: 2,
    tasks: 15,
    rating: 4.2,
    productSales: [7, 8, 7, 8, 7, 8],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 50000, // $950/week * 52
    hourlyRate: 24,
    payType: 'salary',
  },
  {
    name: "Jahidul Islam",
    id: "EMP-1035",
    role: "Store Supervisor",
    shift: "09:00 AM - 05:00 PM",
    clockIn: "9:00 AM",
    status: "Active",
    department: "Sales",
    joined: "March 2022",
    phone: "+880 17YYYYYYYY",
    email: "jahidul@company.com",
    emergency: "017YYYYYYYY",
    defaultShift: "09:00 AM - 05:00 PM",
    avgClockIn: "9:10 AM",
    preferredDayOff: "Saturday",
    totalHours: 410,
    overtime: 1,
    tasks: 13,
    rating: 4.1,
    productSales: [6, 7, 6, 7, 6, 7],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 50000, // $950/week * 52
    hourlyRate: 24,
    payType: 'salary',
  },
  {
    name: "Farzana Yasmin",
    id: "EMP-1036",
    role: "Cashier",
    shift: "10:00 AM - 06:00 PM",
    clockIn: "10:02 AM",
    status: "Absent",
    department: "Sales",
    joined: "April 2020",
    phone: "+880 16YYYYYYYY",
    email: "farzana@company.com",
    emergency: "016YYYYYYYY",
    defaultShift: "10:00 AM - 06:00 PM",
    avgClockIn: "10:15 AM",
    preferredDayOff: "Sunday",
    totalHours: 380,
    overtime: 1,
    tasks: 11,
    rating: 3.8,
    productSales: [5, 6, 5, 6, 5, 6],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 42000, // $800/week * 52
    hourlyRate: 22,
    payType: 'salary',
  },
  {
    name: "Mahmudul Hasan",
    id: "EMP-1037",
    role: "Sales Associate",
    shift: "11:00 AM - 07:00 PM",
    clockIn: "11:15 AM",
    status: "Active",
    department: "Sales",
    joined: "May 2021",
    phone: "+880 15YYYYYYYY",
    email: "mahmudul@company.com",
    emergency: "015YYYYYYYY",
    defaultShift: "11:00 AM - 07:00 PM",
    avgClockIn: "11:25 AM",
    preferredDayOff: "Monday",
    totalHours: 395,
    overtime: 2,
    tasks: 14,
    rating: 4.0,
    productSales: [6, 7, 6, 7, 6, 7],
    productSalesLabels: ["Sun", "Mon", "Tue", "Wed", "Thu", "Apparel"],
    salary: 45000, // $850/week * 52
    hourlyRate: 23,
    payType: 'salary',
  },
];

export function addEmployee(emp: Employee) {
  employees.unshift(emp);
} 